export const data: Record<string, string[]> = {
  PORTUGUES: [
    "Morfologia (substantivo, adjetivo, verbo e advérbio)",
    "Morfologia (preposição, conjunção, artigo, pronome)",
    "Flexão verbal e nominal (tipos e modos dos verbos)",
    "Análise sintática",
    "Concordância nominal e verbal (sintaxe de concordância)",
    "Regência verbal e nominal (sintaxe de regência)",
    "Emprego de Crase",
    "Pontuação",
    "Uso dos porquês",
    "Efeitos de sentido produzidos nos textos. Coesão e coerência textual",
    "Leitura, interpretação e análise de textos de diferentes gêneros textuais, verbais e não",
    "Acentuação gráfica",
    "Grafia dos vocábulos (ortografia)",
  ],
  RACIOCINIO_LOGICO: [
    "Compreensão de estruturas lógicas",
    "Lógica de argumentação: analogias, inferências, deduções e conclusões",
    "Operações com conjuntos",
    "Progressões aritméticas e geométricas",
    "Funções",
    "Razões e proporções",
    "Porcentagem e regra de três",
    "Princípios de contagem e probabilidade",
    "Arranjos e permutações",
    "",
    "",
    "",
    "",
  ],
  INFORMATICA: [
    "Sistema Operacional Windows",
    "Microsoft Word",
    "Microsoft Excel",
    "Microsoft Power Point",
    "Redes de Computadores",
    "Protocolos e Serviços de Internet",
    "Correio Eletrônico",
    "World Wide Web (internet)",
    "Conceitos de Segurança na Internet (tecnologia da informação - segurança da informação)",
    "Procedimentos de Backup",
    "Armazenamento de Dados na Nuvem",
    "Celulares, Tablets e suas Tecnologias (tecnologias com acesso à internet)",
    "Biometria (segurança da informação - Qc)",
  ],
  LEGISLACAO_INSTITUCIONAL: [
    "Lei nº 6.843/1986 (Estatuto do PCSC)",
    "Art. 144 - Segurança Pública (Constituição Federal)",
    "Art. 105 ao 109-A - Da Segurança Pública (Constituição Estadual)",
    "Lei Complementar nº 611/2013 (Subsídio Agente da Autoridade Policial)",
    "Lei nº 16.774/2015 (Jornada de Trabalho e Banco de Horas PCSC)",
    "Lei Complementar nº 491/2010 (Estatuto Jurídico Disciplinar)",
    "Lei Complementar n. 453/2009 (Plano de Carreira)",
    "Lei nº 14.735/2023 (Lei Orgânica Nacional das Polícias Civis)",
    "",
    "",
    "",
    "",
    "",
  ],
  CONSTITUCIONAL: [
    "Conceito de Direito Constitucional: Natureza e Objeto",
    "Art. 1º ao 49 - Princípios fundamentais",
    "Art. 5º - Direitos e deveres individuais e coletivos",
    "Art. 6º ao 11 - Direitos Sociais",
    "Art. 12 e 13 - Direitos de nacionalidade",
    "Art. 14 ao 17 - Direitos políticos e partidos políticos",
    "Art. 37 e 38 - Administração Pública (Disposições Gerais)",
    "Art. 39 ao 42 - Dos Servidores Públicos",
    "Art. 144 - Segurança Pública",
    "Princípios do Direito Constitucional e Princípios",
    "Remédios constitucionais: Habeas Corpus, Habeas Data,",
    "",
    "",
  ],
};
